name: Build and deploy odoc documentation

on:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.1
      - name: Install dependencies with opam
        run: |
          opam install extlib camlzip zarith ocamlbuild goblint-cil
          opam install odoc=2.2.1
      - name: Install dependencies for shake
        run: |
          sudo apt update -y
          sudo apt install cabal-install pkg-config m4 zlib1g-dev -y
          cabal update
          cabal new-install --lib shake
          cabal install --lib base
          cabal install --lib unordered-containers
          cabal install --lib containers
          cabal install --lib directory
          cabal install shake
      - name: Build docs
        run: |
          cd CodeHawk && eval $(opam env) && ~/.local/bin/shake -VV odoc
      - name: Fix permissions
        run: |
          chmod -c -R +rX "CodeHawk/_odoc/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./CodeHawk/_odoc

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
