name: Build and deploy odoc documentation

on:
  push:
    branches:
      - "master"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.1
      - name: Install dependencies with opam
        run: |
          opam install dune extlib camlzip zarith ocamlbuild odoc goblint-cil
      - name: Build docs
        run: |
          cd CodeHawk && eval $(opam env) && dune build @doc
      - name: Fix permissions
        run: |
          chmod -c -R +rX "CodeHawk/_build/default/_doc/_html" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./CodeHawk/_build/default/_doc/_html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
